CHOST="x86_64-pc-linux-gnu"
i686_pc_linux_gnu_CFLAGS="-march=native -O2 -pipe -fPIC"
i686_pc_linux_gnu_CXXFLAGS="-march=native -O2 -pipe -fPIC"
x86_64_pc_linux_gnu_CFLAGS="-march=native -O2 -pipe -fPIC"
x86_64_pc_linux_gnu_CXXFLAGS="-march=native -O2 -pipe -fPIC"

